input {
  beats {
    port => 5044
  }
}

filter {
  grok {
    match => {
      "message" => [
        "INFO:\s+%{IP:client_ip}:%{INT:client_port}\s+-\s+\"%{WORD:method}\s+%{DATA:request}\s+HTTP/%{NUMBER:http_version}\"\s+%{INT:response_code}\s+%{GREEDYDATA:response_message}"
      ]
    }
  }
}

output {

  elasticsearch {

    hosts => ["https://192.168.116.132:9200"]

    user => "elastic"
    password => 'ChQFx-55KYvDlGUOuV+a'

    ssl_certificate_authorities => "/etc/elasticsearch/certs/http_ca.crt"
    ssl_enabled => true

    data_stream => true
    data_stream_type => "logs"
    data_stream_dataset => "fastapi"
    data_stream_namespace => "default"
  }
}